### ISSUE TITLE
Filesystem mutability

### ISSUE THREAD

**Issue by sector-f** [wfraser/fuse-mt#11]
The `fuse::Filesystem` trait methods all take `&mut self`, but the `fuse_mt::FilesystemMT` traits take `&self`. What's the reasoning behind this?  This makes it rather difficult to store a filesystem in memory, which is what I'm trying to do.

**Comment by wfraser** [comment]
Having the methods take `&mut self` would interfere with multi-threading: only one mutable reference can exist at a time. Instead, the implementing struct needs to have internal mutability (i.e. by using `Mutex`) on anything that needs to be mutated.

**Comment by sector-f** [comment]
Yeah, I realized that was probably why after I opened this issue. I ended up forking this crate and removed all the multithreading stuff (but I kept the path -> inode translation stuff, since that's why I decided to use this crate in the first place).

Perhaps it'd be worth writing an example that uses Mutexes or RefCells or something to show how to deal with this.

**Comment by sector-f** [comment]
I haven't worked with multithreading much. Would `std::sync::RwLock` work in place of `Mutex`?

**Comment by wfraser** [comment]
Yep, anything that gives exclusive write access to only one thread at a time.
