### ISSUE TITLE
Remove ino field from FileAttr struct?

### ISSUE THREAD

**Issue by sector-f** [wfraser/fuse-mt#12]
Several functions (at least `getattr` and `lookup`) require returning a `FileAttr`. Part of this `FileAttr` is the inode number as a `u64`, and therefore it seems as if I (as the crate's user) am supposed to keep track of the inode numbers. However, the number I provide in this reply is not what is actually shown by `stat(1)`; I assume that this crate's built-in path -> inode mapping is overriding the inode numbers that I supply.

Because of this, I propose that the `ino` field be removed from the `fuse_mt::FileAttr` struct, as it apparently serves no purpose.

Please tell me if I got any of this wrong!

**Comment by wfraser** [comment]
Ah yes, this is because the `FileAttr` struct is being re-exported from the `rust-fuse` crate. `fuse-mt` manages the value itself; whatever value you put in there is ignored.

You're right, it's probably a good idea to have this crate have its own version of this struct without that field.

**Comment by sector-f** [comment]
Could you add `#[derive(Debug)]` to the new `FileAttr` struct that you created? `fuse::FileAttr` has it

**Comment by wfraser** [comment]
Sure thing. Added in 97ba28f07928837ff5e53bcd6dc561b5e3241013.
