### ISSUE TITLE
Sockets now implemented in fuse-rust

### ISSUE THREAD

**Issue by ERnsTL** [wfraser/fuse-mt#18]
Greetings, regarding your comment in the source `example/src/passthrough.rs`:

  *This is committed to rust-fuse but not yet released. See: https://github.com/zargony/rust-fuse/pull/79*

The mentioned PR was already merged on 2017-01-09 and the following release 0.3.0 was made on 2017-01-25 and thus should include socket support.

**Comment by wfraser** [comment]
zargony/rust-fuse is actually tagged incorrectly... his 0.3.0 tag doesn't correspond to what's actually on crates.io, which is still missing the FileType::Socket variant.

**Comment by ERnsTL** [comment]
I have created a cross-project reference; maybe this can be solved.

**Comment by zargony** [comment]
Weird. I have no idea how that happened, sorry. I just tagged and released 0.3.1

**Comment by wfraser** [comment]
Thanks @zargony and @ERnsTL!

Fixed by 6a1c8921fb949588363eb2b329149c230bcc8c8b.

Released as v0.4.3 (658d25c050b5abb7958fb93d7ae5bddd844fd8ed)
