### ISSUE TITLE
read() seems to have multithreading issues

### ISSUE THREAD

**Issue by pedrocr** [wfraser/fuse-mt#24]
I'm getting inconsistent results from `read()` if I enable multithreading (doesn't happen with just a single thread) and if I do a read() implementation that returns at most 4096 bytes (my block size) even if the program requests more. All my code is safe rust and so far all my filesystem is in memory so there are no external side effects to cause this. Reading `read(2)` it seems it should be legal to return less bytes than requested and it does indeed work fine without threading.

**Comment by wfraser** [comment]
I assume this is your code at https://github.com/pedrocr/syncer/ ?

Can you post exactly what you mean by "inconsistent results"? I.e. what you expect, and what you get?

Can you also post a debug log while reproducing the issue? Fuse-MT and the lower-level FUSE crate use the `log` crate for logging. The simplest way to get debug output is to add the `env_logger` crate to your code, add `env_logger::init();` as the very first line of your main function, and then run your filesystem with the environment variable `RUST_LOG=debug` set.

I haven't yet read through your code, but a common issue when implementing `read` is failing to handle the case where the initial offset of the read is past the end of the file. (This is a perfectly valid thing for the system to do, and you should return zero bytes in this case.) When multithreading is being used, the system might be doing some "prefetching" and reading ahead in the file before it's received data back from earlier calls, and so might go past the end of the file.

**Comment by wfraser** [comment]
Oh, I just read your commit message in https://github.com/pedrocr/syncer/commit/3b633dacfca551f1982aeaea75fa257668c3f389

It sounds like you're expecting to be able to return fewer than the asked-for number of bytes, when in the middle of a file? If you do that, you're saying you're at EOF, and the system won't ask for any more.

**Comment by pedrocr** [comment]
Thanks, that would be it then. The strange bit is that the result was not a shortened fine, just a file with some zeroed out blocks in the middle. I guess the Linux VFS got confused somehow.
