### ISSUE TITLE
FilesystemMT::init default implementation

### ISSUE THREAD

**Issue by zhiburt** [wfraser/fuse-mt#35]
Default implementation of `fuse::Filesystem::init` method in `fuse-rs` lib does _nothing_. But `FilesystemMT::init` by default cases error.

https://github.com/zargony/fuse-rs/blob/39fde4a5c47ce370d228ac190f950bd835db7f47/src/lib.rs#L93-L95

https://github.com/wfraser/fuse-mt/blob/55cda3c7a9e8fcaf975efef3f557b7f562e01533/src/types.rs#L137-L139

https://github.com/wfraser/fuse-mt/blob/55cda3c7a9e8fcaf975efef3f557b7f562e01533/src/fusemt.rs#L97-L100

Why it may be important? Because if you miss the implementation of this method the `fuse-rs` will not work properly. And it's hard to find the issue because it doesn't panic and seemingly works. It just always provides a error `ls: cannot access '': Connection refused`.

If it's considered that method is important it could not have a default implementation at all so it would be required to implement it.

**Comment by wfraser** [comment]
Yeah that's a good point, `init` should probably do nothing and succeed by default, instead of erroring by default.

**Comment by wfraser** [comment]
Thanks for the issue report @zhiburt! Fix will be available in 0.5.1
