### ISSUE TITLE
Feature: Use `OpenOptions` type for `open`

### ISSUE THREAD

**Issue by amosonn** [wfraser/fuse-mt#4]
While idiomitazing things up, I thought maybe some of the argument types should change as well. Every flags-argument which comes as an int would look nicer as a `struct` (or a `bitfield`, when that enters the language).

For some of them, this means adding dedicated types, but specifically for `open` we have `OpenOptions` which is used by the stdlib for passing flags to `open`.

The implementation is of course straight-forward, I wanted to ask what you think about this beforehand.

**Comment by wfraser** [comment]
Unfortunately `OpenOptions` doesn't encapsulate anywhere near all the things that can be passed in the `flags` argument to `open`. Take a look at the list in `man 2 open` for an idea of all the things that can be in there. I think doing that would unnecessarily restrict the things that a filesystem can do.

**Comment by amosonn** [comment]
Well, `OpenOptions` in Linux also has an `extra flags` for this purpose. The bigger problem I've noticed is that it is the "reverse" of what we need, in a sense - having API to set options (and internal API to get this as flags), not to get them (and internal to parse).

However, I still think that having a custom structure and parsing the flags into it is reasonable for getting a more idiomatic API. This struct can support all the flags, or (as in `OpenOptions`) support only the important ones, leaving the others as a c-flags. Note that most of the fancy flags are directed at the kernel more than at the fs, and in most use cases, the fs shouldn't care about them.

The other obvious candidate is `mode`.
